


 /*Donner la/les photos avec la balise 'plage' trié par ordre décroissant */

SELECT P.CODE, P.LIEU_REALISATION, P.DATE_REALISATION
    FROM PHOTOGRAPHIE P
    INNER JOIN MARQUER M ON P.CODE = M.CODEPHOTOMARQUER
    INNER JOIN BALISE B ON M.BALISE_MARQUER = B.TYPE_BALISE
    WHERE B.TYPE_BALISE = 'plage'
    ORDER BY P.DATE_REALISATION DESC; 



/* Donner le nombre de commentaires pour chaque photos  */

SELECT P.CODE, P.LIEU_REALISATION, P.DATE_REALISATION, COUNT(C.IDCOMMENTAIRE) AS COMMENT_COUNT
    FROM PHOTOGRAPHIE P
    INNER JOIN COMMENTAIRE C ON P.CODE = C.CODEPHOTOCOM
    GROUP BY P.CODE, P.LIEU_REALISATION, P.DATE_REALISATION
    ORDER BY COMMENT_COUNT DESC;


/*  Donner la/les photos prises avec le flash à Montpellier en 2023 */

SELECT P.CODE, P.LIEU_REALISATION, P.DATE_REALISATION
    FROM PHOTOGRAPHIE P
    INNER JOIN CONFIG C ON P.IDCONF = C.IDCONF
    WHERE P.LIEU_REALISATION = 'Montpellier'
    AND P.DATE_REALISATION >= '01/01/2023' AND P.DATE_REALISATION <= '31/12/2023'
    AND C.FLASH = 1;

/*  Donner la/les photos prise avec la même configuration et le même appareil que la photo n°3000 */

SELECT P.CODE, P.LIEU_REALISATION, P.DATE_REALISATION
    FROM PHOTOGRAPHIE P
    WHERE P.CODE <> 3000 
    AND P.IDAPPAREIL = (SELECT IDAPPAREIL FROM PHOTOGRAPHIE WHERE CODE = 3000)
    AND P.IDCONF = (SELECT IDCONF FROM PHOTOGRAPHIE WHERE CODE = 3000);


/* Donner la requête qui permet de trouver les photos les plus appréciées avec la licence de distribution
’tous droits réservés’*/

SELECT P.CODE, P.LIEU_REALISATION, P.DATE_REALISATION, P.LICENCE, COUNT(A.ID_UTIL_LIKE) AS LIKE_COUNT
    FROM PHOTOGRAPHIE P
    INNER JOIN AIME A ON P.CODE = A.CODEPHOTOLIKE
    WHERE P.LICENCE = 'tous droits reserves'
    GROUP BY P.CODE, P.LIEU_REALISATION, P.DATE_REALISATION, P.LICENCE
    HAVING COUNT(A.ID_UTIL_LIKE) = (
        SELECT MAX(LIKE_COUNT)
            FROM (
            SELECT P2.CODE, COUNT(A2.ID_UTIL_LIKE) AS LIKE_COUNT
            FROM PHOTOGRAPHIE P2
            INNER JOIN AIME A2 ON P2.CODE = A2.CODEPHOTOLIKE
            WHERE P2.LICENCE = 'tous droits reserves'
            GROUP BY P2.CODE, P2.LICENCE
            )
        );


/* Donner la requête qui permet de trouver les photos incluses dans le plus grande nombre de galeries. */

SELECT R.CODEPHOTO, P.LIEU_REALISATION, P.DATE_REALISATION, COUNT(*) AS GALLERY_COUNT
    FROM RANGER R
    INNER JOIN GALERIE G ON R.IDCOLLECTION = G.IDGAL
    INNER JOIN PHOTOGRAPHIE P ON R.CODEPHOTO = P.CODE
    GROUP BY R.CODEPHOTO, P.LIEU_REALISATION, P.DATE_REALISATION
    ORDER BY GALLERY_COUNT DESC;
