/*Suppression des données */

DELETE FROM UTILISATEUR ;
DELETE FROM APPAREIL;
DELETE FROM CONFIG;
DELETE FROM PHOTOGRAPHIE;
DELETE FROM COLLECT;
DELETE FROM ALBUM;
DELETE FROM GALERIE;
DELETE FROM RANGER;
DELETE FROM CONTENU_NUMERIQUE;
DELETE FROM DISCUSSION;
DELETE FROM AIME;
DELETE FROM ABONNE;
DELETE FROM COMMENTAIRE;
DELETE FROM VISUALISE;
DELETE FROM PUBLIE;
DELETE FROM BALISE;
DELETE FROM MARQUER;


/*Suppresion des tables   */

DROP TABLE UTILISATEUR  CASCADE CONSTRAINTS;
DROP TABLE APPAREIL  CASCADE CONSTRAINTS;
DROP TABLE CONFIG  CASCADE CONSTRAINTS;
DROP TABLE PHOTOGRAPHIE  CASCADE CONSTRAINTS;
DROP TABLE COLLECT  CASCADE CONSTRAINTS;
DROP TABLE ALBUM  CASCADE CONSTRAINTS;
DROP TABLE GALERIE  CASCADE CONSTRAINTS;
DROP TABLE RANGER  CASCADE CONSTRAINTS;
DROP TABLE CONTENU_NUMERIQUE  CASCADE CONSTRAINTS;
DROP TABLE DISCUSSION  CASCADE CONSTRAINTS;
DROP TABLE AIME  CASCADE CONSTRAINTS;
DROP TABLE ABONNE  CASCADE CONSTRAINTS;
DROP TABLE COMMENTAIRE  CASCADE CONSTRAINTS;
DROP TABLE VISUALISE  CASCADE CONSTRAINTS;
DROP TABLE PUBLIE  CASCADE CONSTRAINTS;
DROP TABLE BALISE  CASCADE CONSTRAINTS;
DROP TABLE MARQUER  CASCADE CONSTRAINTS;
